### ISSUE TITLE
CLI tool for aggregating single cell data

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#1264]
## TODO

- [x] aggregate any single cell vectors or the preferred ones if unspecified
- [x] aggregate by a given cell type assignment or the preferred one if unspecified
- [ ] aggregate by any cell-level characteristics (optional)
- [ ] aggregate by multiple characteristics (very optional)
- [x] add a switch to make the resulting raw QT preferred
- [ ] add appropriate audit trail events describing how the aggregation was done and with data vectors and annotations were used
- [x] support deleting aggregated data
- [x] indicate that the data is in CPM
- [x] switch COUNT to LINEAR or maybe compute log2cpm outright
- [ ] investigate if we could include normalization factors (optional)

**Comment by arteymix** [comment]
This is done, I'm just doing a little bit more testing at this point.

**Comment by arteymix** [comment]
I'm almost done with deleting aggregated data. There's a few caveat to consider such as whether to remove the dimension and resetting the single-cell metrics (see #1273), but also deleting generated data files for that QT.

**Comment by arteymix** [comment]
Good, now we can reliably aggregate and delete aggregated vectors! I'm looking into some -Infinity slipping through the aggregation process and causing the processed vectors to be filled with NaNs...

I've also made some improvements to which file get deleted when regenerating a platform annotations and pre-processing an experiment.

**Comment by arteymix** [comment]
Ok got the NaN situation figured out. We need to adjust the data to the library size and add a pseudocount just like we do for log2cpm of RNA-Seq data.

**Comment by arteymix** [comment]
Counting data would become linear after library size normalization.

Linear data would technically not be CPM, but I don't think that is important.

We also need to look into allowing count data to use a logarithmic scale type. We might find counting data out there that is unfortunately already log-transformed.

**Comment by arteymix** [comment]
Another thing to include in the tests is non-integer counting data.

This happens for some method that regresses out ambient RNA or other contaminants from the data. This we would get a general type COUNT and a scale type LINEAR, or something similar. We can add a way to generate such vectors by adding a little bit of multiplicative Gaussian noise.
