### ISSUE TITLE
Remove unused/unneeded fields in our VO models

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/Gemma#311]
This can be done in two ways: by removing the field altogether, or by using Jackson's `@JsonIgnore` annotation to hide it for the JSON serialization.

 - [x] remove Gene name and description (see #292)
 - [x] https://github.com/PavlidisLab/Gemma/issues/428: This is used in GemmaDE so it'd be nice to have a way to get it (according to @oganm) 
 - [x] hide incorrect statistics at result set level #422

The entities can be reviewed here: https://dev.gemma.msl.ubc.ca/resources/restapidocs/index.html (requires VPN access)

Let's be especially aware of [gemma.R parsing](https://github.com/PavlidisLab/gemma.R/blob/master/R/processors.R) to not remove things it expects to be present.

**Comment by arteymix** [comment]
@ppavlidis also noted that some fields are not filled, which might occur in cases where they are used elsewhere, but forking the VO wasn't deemed useful. We can either fill the field or hide it.

**Comment by arteymix** [comment]
@oganm If you can provide me with the fields that we should exclude in the API, that would be really helpful. We can annotate then in the code with [@JsonIgnore](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/latest/com/fasterxml/jackson/annotation/JsonIgnore.html).

**Comment by oganm** [comment]
Will be looking endpoint by enpoint and pointing out the fields that are always NULL. Will continue next week but here's one I went through. Do let me know if there is a better way to share this.

## Endpoint
https://dev.gemma.msl.ubc.ca/resources/restapidocs/index.html#/default/getPlatformsByIds


### Nulls that would be useful

numGenes

### Nulls that could be useful

designElementCount
isMerged
isSubsumer
isSubsumed
numProbeAlignments
numProbeSequences
numProbesToGenes


### Nulls that are better of removed
dateCached


### Nulls that I am unclear on
hasBlatAssociations
hasGeneAssociations
hasSequenceAssociations
lastGeneMapping
lastRepeatMask
lastSequenceAnalysis
lastSequenceUpdate

**Comment by arteymix** [comment]
Cool! It's fine if we hide them because I don't expect being filling those in this release.

We can consider filling those in the 1.29.

**Comment by arteymix** [comment]
Hmm, numGenes in ArrayDesignValueObject is a string... do you want this property? I can also create another property: numberOfGenes with the proper type.

**Comment by arteymix** [comment]
Filling isSubsumer/isSubsumed and isMerged require extra database query. I'll evaluate those for the next release.

**Comment by arteymix** [comment]
I excluded all the properties you mentioned and created numberOfGenes. If there are properties that would definitly be useful, please let me know @oganm so that I can expose them. Note that they all come at an extra cost.

**Comment by ppavlidis** [comment]
Platform Subsumer/subsumed is not important for R/python users but would be used in our own web site. Merge/mergee is more important. Both are really only relevant to microarrays.

The meaning of this is documented elsewhere but briefly, we use tests of subsuming (a platform contains all the sequences on another platform) to identify candidates for merging. This is useful because if we have a single "top-level" platform that covers the sequences on "child platforms" when we do sequence analysis we only have to analyze the top-level one.

**Comment by arteymix** [comment]
Ok, the annotations from Jackson I'm applying here are not affecting the website. I'll see if we can borrow the initialization code for the merged/mergee state.

isMergee is cheap to compute because we only need to check if the column differs from NULL. The counterpart requires a count(...) query.

**Comment by arteymix** [comment]
@oganm Maybe the next big one would be ExpressionExperimentValueObject?

**Comment by ppavlidis** [comment]
> Ok, the annotations from Jackson I'm applying here are not affecting the website. I'll see if we can borrow the initialization code for the merged/mergee state.
> 
> isMergee is cheap to compute because we only need to check if the column differs from NULL. The counterpart requires a count(...) query.

isMerged doesn't require a count. Neither do the subsuming attributes.

**Comment by arteymix** [comment]
You have to do mergees.isEmpty(), which is equivalent to counting the number of AD where the mergee is the AD in question and equating it to zero. The efficient implementation checks all ADs in a given collection at once. I'll use that.

**Comment by arteymix** [comment]
What about isAffymetrixAltCdf and hasSequenceAssociations? blackListed does not seem super useful since we shouldn't display them anyway.

**Comment by ppavlidis** [comment]
Those aren't very important. Blacklisted platforms shouldn't be shown as you say.

**Comment by arteymix** [comment]
Ok, I'm done with ArrayDesignValueObject for now. I'll work on other 1.28 issues now.

**Comment by arteymix** [comment]
The null fields in EEVO (from /rest/v2/datasets):

- arrayDesignCount
- bioMaterialCount

I'm hiding the securable VO stuff as well as currentUserHasWritePermission and currentUserIsOwner.

- experimentalDesign is an ID, maybe we should rename it to experimentalDesignId in the serialization?
- isPublic, isShared?
- metadata
- suitableForDEA? why is that relevant?
- processedExpressionVectorCount, but no rawExpressionVectorCount, if it's the same, then we should just name it expressionVectorCount

@oganm let me know if these are used in gemma.R.

**Comment by ppavlidis** [comment]
Don't know if I'm helping or not but:
- arrayDesignCount is not so useful. It should always be 1 for a fully-curated experiment.
- bioMaterial count is redundant with bioAssay count (if that's there) for fully-curated experiments, because we simplify experiments to have one biomaterial for each bioassay.
- technologyType is useful
- experimentalDesignID might not be all that useful, because retrieving experimental design details is actually done via the experiment. I doubt R/python users would ever need that.
- isPublic/isShared are not relevant to users especially if they are not administrators.
- I agree about processed vectors, maybe naming it "expressionProfileCount" would be even more intuitive. (But this usually (always?) is the same as the number of elements on the platform used)
- metadata is probably supposed to have details of how the experiment was processed i.e. RNA-seq pipeline info? But I'm not sure that was ever fully implemented.

**Comment by oganm** [comment]
Think you just touched on this but here's my look

## Endpoint
https://dev.gemma.msl.ubc.ca/resources/restapidocs/index.html#/default/getDatasetsByIds

This endpoint could benefit from including the platform ID(s) too if it doesn't add too much of an overhead, but it's hardly essential

### Nulls that would be useful


### Nulls that could be useful



### Nulls that are better of removed
technologyType
metadata: Not sure what this was supposed to include 

### Nulls that I am unclear on

**Comment by oganm** [comment]
Think you just touched on this but here's my look

## Endpoint
https://dev.gemma.msl.ubc.ca/resources/restapidocs/index.html#/default/getResultSets



### Nulls that would be useful


### Nulls that could be useful
analysis.sourceExperiment


### Nulls that are better of removed

Think all of these are reduntant with the components of experimentalFactors or reduntant with the specialised call

analysis.factorValuesUsed
analysis.arrayDesignsUsed
analysis.resultSets: don't think the intent is to include the whole result set object here

### Nulls that I am unclear on

**Comment by arteymix** [comment]
I'll remove `numberOfGenes` and hide `numGenes` finally. There's a service that can populate these, so I might consider doing just that in the next release.

**Comment by oganm** [comment]
## Endpoint

https://dev.gemma.msl.ubc.ca/resources/restapidocs/index.html#/default/getGenes

## Nulls that would be useful

## Null that could be useful
aliases: but probably too much work for an endpoint like this
homologues: but probably too much work for an endpoint like this

## Nulls that are better of removed
platformCount: probably not worth the overhead


## Nulls that I am unclear on
geneSets
nodeDegreeNegRanks
nodeDegreePosRanks
nodeDegreesNeg
nodeDegreesPos
phenotypes
score

**Comment by oganm** [comment]
## Endpoint

https://dev.gemma.msl.ubc.ca/resources/restapidocs/index.html#/default/getGeneLocations

## Nulls that would be useful
id: Not sure if this is supposed to be the ID of the original queried gene but if it is, it might be nice to get it to know which gene we are looking at.


## Nulls that are better of removed

taxon.isSpecies: is this ever not true?

**Comment by ppavlidis** [comment]
> ## Endpoint
> https://dev.gemma.msl.ubc.ca/resources/restapidocs/index.html#/default/getGenes
> 
> ## Nulls that would be useful
> gene.MFX.Rank: This is used in GemmaDE so it'd be nice to have a way to get it
> 
> ## Null that could be useful
> aliases: but probably too much work for an endpoint like this homologues: but probably too much work for an endpoint like this numGoTerms: not null but always returns a 0. there is a separate endpoint to get gene GOs which might be the better place to go
> 
> ## Nulls that are better of removed
> platformCount: probably not worth the overhead
> 
> ## Nulls that I am unclear on
> geneSets nodeDegreeNegRanks nodeDegreePosRanks nodeDegreesNeg nodeDegreesPos phenotypes score

Those last 7 can be dropped

Platformcount should always be 1 for a fully curated dataser

**Comment by ppavlidis** [comment]
Ispecies can be false but it's not currently necessary.

**Comment by arteymix** [comment]
Gene is almost done now! I've filled multifunctionality ranks and now finishing up aliases.

**Comment by arteymix** [comment]
Gene VO is fixed in ac70203c2eab8f7616ec02c7eba712a3c06a3b09

**Comment by arteymix** [comment]
I'm taking a good look overall now.

Deprecated endpoints looks nice in Swagger UI:

![image](https://user-images.githubusercontent.com/1318477/192366312-90e3e0a1-8a83-48bf-8ca4-fc1ae85e7e19.png)

**Comment by arteymix** [comment]
@oganm would this break the R client if I were to rename the GeeqValueObject properties?

![image](https://user-images.githubusercontent.com/1318477/192394308-bb00f8d9-d08d-43d1-a06b-5b3b9eaec62f.png)

**Comment by oganm** [comment]
Yes but only until I fix them. Wouldn't worry about it if the dev and production will be in sync  before the bioconductor's feature freeze

**Comment by arteymix** [comment]
I don't even know if I can fix those without breaking the frontend... Let me check how DWR serialize this VO...

**Comment by arteymix** [comment]
Ok, good, I can change this without breaking the frontend. DWR actually handles our incorrect camel-case.

**Comment by arteymix** [comment]
Ok, this is done!
